module.exports = {
    "bulk_listings": [
      {
        "listing_info": {
       
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },
      {
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      },{
        "listing_info": {
          "business_name": "Hilton Los Angeles Airport",
          "business_website": "http://www3.hilton.com",
          "business_emails": [
            ""
          ],
          "business_local_phone": [
            "3104104000"
          ],
          "address_street_address": "5711 West Century Boulevard",
          "locality": "Los Angeles",
          "region": "CA",
          "postal_code": "90045",
          "country_code": "us",
          "buzz_partner_id": 1974
        },
        "product_primary_key": 2603639
      }
    ],
    "custom_args": {
      "partner_id": 1974,
      "user_id": 17982,
      "listing_type": "BulkUpload"
    },
    "signals": [
      "page_video",
      "page_video_count",
      "cart",
      "page_meta_description",
      "buying_page",
      "page_googleplaces",
      "local_directory_googleplaces_presence",
      "local_directory_googleplaces_address",
      "local_directory_googleplaces_api_name",
      "local_directory_googleplaces_api_response",
      "local_directory_googleplaces_business_id",
      "local_directory_googleplaces_business_name",
      "local_directory_googleplaces_business_name_match",
      "local_directory_googleplaces_is_claimed",
      "local_directory_googleplaces_locality_match",
      "local_directory_googleplaces_match_level",
      "local_directory_googleplaces_phone_number",
      "local_directory_googleplaces_phone_number_match",
      "local_directory_googleplaces_region_match",
      "local_directory_googleplaces_street_address_match",
      "local_directory_googleplaces_page_url",
      "reservation_and_booking",
      "page_heading_included",
      "page_headings_description",
      "selling_page",
      "local_directory_yahoolocal_presence",
      "local_directory_yahoolocal_address",
      "local_directory_yahoolocal_api_name",
      "local_directory_yahoolocal_api_response",
      "local_directory_yahoolocal_business_id",
      "local_directory_yahoolocal_business_name",
      "local_directory_yahoolocal_business_name_match",
      "local_directory_yahoolocal_is_claimed",
      "local_directory_yahoolocal_locality_match",
      "local_directory_yahoolocal_match_level",
      "local_directory_yahoolocal_phone_number",
      "local_directory_yahoolocal_phone_number_match",
      "local_directory_yahoolocal_ratings",
      "local_directory_yahoolocal_region_match",
      "local_directory_yahoolocal_reviews",
      "local_directory_yahoolocal_street_address_match",
      "page_yahoolocal",
      "local_directory_yahoolocal_page_url",
      "online_ordering",
      "page_alt_count",
      "page_image_optimization",
      "page_images_count",
      "rentals_page",
      "local_directory_binglocal_presence",
      "local_directory_binglocal_address",
      "local_directory_binglocal_api_name",
      "local_directory_binglocal_api_response",
      "local_directory_binglocal_business_id",
      "local_directory_binglocal_business_name",
      "local_directory_binglocal_business_name_match",
      "local_directory_binglocal_is_claimed",
      "local_directory_binglocal_locality_match",
      "local_directory_binglocal_match_level",
      "local_directory_binglocal_phone_number",
      "local_directory_binglocal_phone_number_match",
      "local_directory_binglocal_ratings",
      "local_directory_binglocal_region_match",
      "local_directory_binglocal_reviews",
      "local_directory_binglocal_street_address_match",
      "local_directory_binglocal_page_url",
      "adwords_data_semrush_AdwordsKeywords",
      "adwords_data_semrush_OrganicTraffic",
      "adwords_data_semrush_Rank",
      "total_paid_keywords",
      "total_organic_keywords",
      "total_adwords_history",
      "total_domain_ad_history",
      "total_competitors_paid_keywords",
      "competitors_organic_keywords",
      "total_competitors_organic_keywords",
      "topads",
      "total_topads",
      "adwords_traffic",
      "adwords_cost",
      "adwords_analyzed_date",
      "adwords_data_semrush_Database",
      "adwords_date",
      "adwords_data_semrush_Domain",
      "adwords_month",
      "adwords_data_semrush_OrganicCost",
      "adwords_data_semrush_OrganicKeywords",
      "paid_keywords",
      "organic_keywords",
      "adwords_history",
      "domain_ad_history",
      "competitors_paid_keywords",
      "page_citygrid",
      "local_directory_citygrid_presence",
      "local_directory_citygrid_address",
      "local_directory_citygrid_api_name",
      "local_directory_citygrid_api_response",
      "local_directory_citygrid_business_id",
      "local_directory_citygrid_business_name",
      "local_directory_citygrid_business_name_match",
      "local_directory_citygrid_is_claimed",
      "local_directory_citygrid_locality_match",
      "local_directory_citygrid_match_level",
      "local_directory_citygrid_phone_number",
      "local_directory_citygrid_phone_number_match",
      "local_directory_citygrid_ratings",
      "local_directory_citygrid_region_match",
      "local_directory_citygrid_reviews",
      "local_directory_citygrid_street_address_match",
      "local_directory_citygrid_page_url",
      "page_wordpress",
      "promotions",
      "page_frames_excluded",
      "estimates_page",
      "local_directory_yellowpages_presence",
      "local_directory_yellowpages_address",
      "local_directory_yellowpages_api_name",
      "local_directory_yellowpages_api_response",
      "local_directory_yellowpages_business_id",
      "local_directory_yellowpages_business_name_match",
      "local_directory_yellowpages_locality_match",
      "local_directory_yellowpages_phone_number",
      "local_directory_yellowpages_ratings",
      "local_directory_yellowpages_region_match",
      "local_directory_yellowpages_street_address_match",
      "local_directory_yellowpages_business_name",
      "local_directory_yellowpages_is_claimed",
      "local_directory_yellowpages_match_level",
      "local_directory_yellowpages_phone_number_match",
      "local_directory_yellowpages_reviews",
      "local_directory_yellowpages_page_url",
      "page_google_analytics",
      "about_page",
      "page_flash_excluded",
      "page_flash_count",
      "menu",
      "bing_cost",
      "bing_data_semrush_OrganicTraffic",
      "bing_traffic",
      "bing_data_semrush_Database",
      "bing_data_date",
      "bing_data_semrush_Domain",
      "bing_adwords_month",
      "bing_data_semrush_OrganicCost",
      "bing_data_semrush_OrganicKeywords",
      "bing_data_semrush_Rank",
      "page_www_resolve",
      "page_sensitive_information_security",
      "page_secured_site",
      "services_page",
      "page_backlinks",
      "page_trustflow",
      "responsive_screen",
      "robots",
      "blog",
      "form",
      "bing_data_semrush_AdwordsKeywords",
      "page_sitemap_xml",
      "gallery",
      "insurances_accepted",
      "google_indexed_pages_count",
      "google_indexed_image_path",
      "google_indexed_content_path",
      "google_indexed_source",
      "page_phone_number_on_page",
      "page_text_content",
      "certifications",
      "yahoo_indexed_pages",
      "yahoo_indexed_image_path",
      "yahoo_indexed_content_path",
      "yahoo_indexed_source",
      "page_address_on_page",
      "business_hours",
      "page_social_mentions",
      "bing_indexed_pages_count",
      "bing_indexed_image_path",
      "bing_indexed_content_path",
      "bing_indexed_source",
      "map",
      "local_directory_noikiaplaces_presence",
      "local_directory_noikiaplaces_address",
      "local_directory_noikiaplaces_api_name",
      "local_directory_noikiaplaces_api_response",
      "local_directory_noikiaplaces_business_id",
      "local_directory_noikiaplaces_business_name",
      "local_directory_noikiaplaces_business_name_match",
      "local_directory_noikiaplaces_is_claimed",
      "local_directory_noikiaplaces_locality_match",
      "local_directory_noikiaplaces_match_level",
      "local_directory_noikiaplaces_phone_number",
      "local_directory_noikiaplaces_phone_number_match",
      "local_directory_noikiaplaces_region_match",
      "local_directory_noikiaplaces_street_address_match",
      "local_directory_noikiaplaces_page_url",
      "faq",
      "page_seo_friendly_url",
      "page_bb_mobile_compatible",
      "page_bb_mobile_url",
      "page_google_mobile_friendly",
      "contact_address",
      "contact_page",
      "domain_whois",
      "page_domain_age",
      "domain_data_domain_length",
      "domain_data_final_host",
      "domain_data_final_website",
      "domain_data_google_reachable",
      "host_name",
      "domain_data_http_status_codes",
      "domain_data_ipv4",
      "domain_data_lastmodified_date_sec",
      "domain_data_main_domain",
      "domain_data_proper_hostname",
      "domain_data_redirect_count",
      "domain_data_redirect_host",
      "domain_data_redirected_url",
      "domain_data_scheme",
      "domain_data_tld",
      "domain_valid",
      "domain_data_valid_host",
      "domain_data_valid_url",
      "domain_registrant",
      "domain_registration",
      "domain_name_servers",
      "domain_record_source",
      "domain_http_redirects",
      "testimonials",
      "page_sitemap_html",
      "facebook_page",
      "page_facebook_widget",
      "facebook_likes",
      "facebook_link",
      "facebook_location_city",
      "facebook_location_country",
      "facebook_location_latitude",
      "facebook_location_longitude",
      "facebook_location_state",
      "facebook_location_street",
      "facebook_location_zip",
      "facebook_name",
      "facebook_page_url",
      "facebook_phone",
      "facebook_posts",
      "facebook_posts_counts",
      "facebook_shares_count",
      "facebook_source",
      "facebook_talking_about_count",
      "facebook_username",
      "facebook_website",
      "facebook_were_here_count",
      "facebook_affiliation",
      "facebook_app_links",
      "facebook_artists_we_like",
      "facebook_attire",
      "facebook_awards",
      "facebook_band_interests",
      "facebook_band_members",
      "facebook_best_page",
      "facebook_bio",
      "facebook_birthday",
      "facebook_booking_agent",
      "facebook_built",
      "facebook_can_checkin",
      "facebook_can_post",
      "facebook_category_list",
      "facebook_company_overview",
      "facebook_cover",
      "facebook_current_location",
      "facebook_description",
      "facebook_description_html",
      "facebook_directed_by",
      "facebook_display_subtext",
      "facebook_displayed_message_response_time",
      "facebook_emails",
      "facebook_engagement_count",
      "facebook_featured_video",
      "facebook_features",
      "facebook_food_styles",
      "facebook_founded",
      "facebook_general_info",
      "facebook_general_manager",
      "facebook_genre",
      "facebook_global_brand_page_name",
      "facebook_has_added_app",
      "facebook_hometown",
      "facebook_hours",
      "facebook_impressum",
      "facebook_influences",
      "facebook_is_always_open",
      "facebook_is_community_page",
      "facebook_is_permanently_closed",
      "facebook_is_published",
      "facebook_is_webhooks_subscribed",
      "facebook_leadgen_tos_accepted",
      "facebook_members",
      "facebook_merchant_review_status",
      "facebook_mission",
      "facebook_mpg",
      "facebook_name_with_location_descriptor",
      "facebook_network",
      "facebook_overall_star_rating",
      "facebook_parent_page",
      "facebook_parking",
      "facebook_payment_options",
      "facebook_personal_info",
      "facebook_personal_interests",
      "facebook_place_type",
      "facebook_plot_outline",
      "facebook_press_contact",
      "facebook_price_range",
      "facebook_produced_by",
      "facebook_products",
      "facebook_picture",
      "facebook_public_transit",
      "facebook_rating_count",
      "facebook_record_label",
      "facebook_release_date",
      "facebook_restaurant_services",
      "facebook_restaurant_specialties",
      "facebook_schedule",
      "facebook_screenplay_by",
      "facebook_season",
      "facebook_single_line_address",
      "facebook_starring",
      "facebook_start_info",
      "facebook_store_number",
      "facebook_verification_status",
      "facebook_last_engagement_date",
      "facebook_about",
      "facebook_category",
      "facebook_checkins",
      "facebook_id",
      "facebook_is_unclaimed",
      "facebook_is_verified",
      "facebook_leadgen_tos_acceptance_time",
      "facebook_leadgen_tos_accepting_user",
      "facebook_store_location_descriptor",
      "facebook_studio",
      "facebook_voip_info",
      "facebook_posting_frequency",
      "facebook_posting_frequency_value",
      "facebook_average_posting_count",
      "facebook_engagement_trend.daily",
      "facebook_written_by",
      "page_cache_enabled",
      "page_file_compression",
      "page_server_response_time",
      "page_speed_score",
      "page_image_size_optimization",
      "page_domain_redirection",
      "page_prioritize_visible_content",
      "page_coupouns",
      "privacy_policy",
      "mobile_pagespeed_score",
      "new_cars_page",
      "newsletter",
      "page_twitter_widget",
      "twitter_display_name",
      "twitter_posts",
      "twitter_posts_count",
      "twitter_followers",
      "twitter_following",
      "twitter_following_count",
      "twitter_id",
      "twitter_location",
      "twitter_page_url",
      "twitter_screen_name",
      "twitter_tweets",
      "twitter_url",
      "twitter_description",
      "twitter_protected",
      "twitter_time_zone",
      "twitter_verified",
      "twitter_lang",
      "twitter_status",
      "twitter_contributors_enabled",
      "twitter_is_translator",
      "twitter_profile_background_image_url_https",
      "twitter_profile_sidebar_border_color",
      "twitter_profile_sidebar_fill_color",
      "twitter_profile_text_color",
      "twitter_profile_use_background_image",
      "twitter_has_extended_profile",
      "twitter_default_profile",
      "twitter_default_profile_image",
      "twitter_follow_request_sent",
      "twitter_notifications",
      "twitter_translator_type",
      "twitter_last_engagement_date",
      "twitter_posting_frequency",
      "twitter_posting_frequency_value",
      "twitter_average_posting_count",
      "twitter_engagement_trend.daily",
      "twitter_page",
      "twitter_id_str",
      "twitter_entities_description_urls",
      "twitter_listed_count",
      "twitter_created_at",
      "twitter_favourites_count",
      "twitter_utc_offset",
      "twitter_geo_enabled",
      "twitter_is_translation_enabled",
      "twitter_profile_background_color",
      "twitter_profile_background_image_url",
      "twitter_profile_background_tile",
      "twitter_profile_image_url",
      "twitter_profile_image_url_https",
      "twitter_profile_link_color",
      "get_a_quote",
      "page_title_tag_compliance",
      "page_meta_tag_compliance",
      "page_meta_title",
      "used_cars_page",
      "youtube_comment_count",
      "youtube_hidden_subscriber_count",
      "youtube_id",
      "youtube_page_url",
      "youtube_subscriber_count",
      "youtube_video_count",
      "youtube_view_count",
      "youtube_page",
      "scheduler",
      "page_location_in_title",
      "finance",
      "linkedin_page",
      "mortgage_calculator",
      "page_unique_title",
      "page_unique_title_cnt",
      "page_unique_title_cnt_links",
      "page_unique_title_total_links",
      "page_unique_title_total_links_cnt",
      "inventory_search_form",
      "display_ads_ad_metrics",
      "display_ads_mobile_creatives",
      "display_ads_desktop_creatives",
      "display_ads_total_ads_by_ad_type",
      "display_ads_impressions",
      "display_ads_adspend",
      "display_ads_networks",
      "technologies_ad_servers",
      "technologies_advertising_networks",
      "technologies_affiliate_advertising_network",
      "technologies_analytics_and_tracking",
      "technologies_appointment_scheduling",
      "technologies_call_tracking",
      "technologies_captcha",
      "technologies_chats",
      "technologies_cloud_services_",
      "technologies_cms",
      "technologies_comments",
      "technologies_content_delivery_networks",
      "technologies_content_syndication_networks",
      "technologies_css_and_javascript_libraries",
      "technologies_customer_relationship_management",
      "technologies_customer_reviews",
      "technologies_data_management_platform",
      "technologies_demand_side_platforms",
      "technologies_domain_name_services",
      "technologies_e-commerce_platforms",
      "technologies_e-commerce_tools",
      "technologies_email_delivery",
      "technologies_email_marketing",
      "technologies_email_providers",
      "technologies_event_management",
      "technologies_fonts",
      "technologies_food_ordering_services",
      "technologies_frameworks_and_programming_languages",
      "technologies_gigya",
      "technologies_hosted_forms",
      "technologies_social_login",
      "technologies_social_media_marketing",
      "technologies_social_sharing",
      "technologies_ssl_certificates",
      "technologies_supply_side_platforms",
      "technologies_support_and_feedback",
      "technologies_tag_management",
      "technologies_video_advertising_networks",
      "technologies_web_accelerators",
      "technologies_web_performance_monitoring",
      "technologies_web_presentation_tools",
      "technologies_widgets",
      "technologies_hosting",
      "technologies_lead_generation_software",
      "technologies_learning_management_systems",
      "technologies_live_streaming_platforms",
      "technologies_load_balancers",
      "technologies_loyalty_and_gamification",
      "technologies_marketing_automation",
      "technologies_miscellaneous",
      "technologies_online_testing_platforms",
      "technologies_online_video_platforms",
      "technologies_payments",
      "technologies_personalization",
      "technologies_publisher_advertising_tools",
      "technologies_recruitment",
      "technologies_reservation_software",
      "technologies_retargeting",
      "technologies_search_appliances",
      "technologies_search_marketing",
      "technologies_security",
      "technologies_site_and_cart_abandonment",
      "technologies_site_delivery",
      "technologies_small_business_marketing_software",
      "technologies"
    ],
    "product_callback_url": "http://cron1.buzzboard.com/callback.php"
  }